/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function HeroModel(props) {
  const { nodes, materials } = useGLTF("/hero.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.86, -1.21]}
        rotation={[-3.08, 0, Math.PI]}
        scale={2.35}
      >
        <primitive object={nodes.spine} />
        <primitive object={nodes.neutral_bone} />
        <primitive object={nodes.neutral_bone_1} />
        <primitive object={nodes.neutral_bone_2} />
        <primitive object={nodes.neutral_bone_3} />
        <primitive object={nodes.neutral_bone_4} />
        <skinnedMesh
          geometry={nodes.Cube021.geometry}
          material={materials["Skin.001"]}
          skeleton={nodes.Cube021.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube022.geometry}
          material={materials["Material.026"]}
          skeleton={nodes.Cube022.skeleton}
        />
        <skinnedMesh
          geometry={nodes.M_Hips.geometry}
          material={materials.Skin}
          skeleton={nodes.M_Hips.skeleton}
        />
        <skinnedMesh
          geometry={nodes.NurbsPath011.geometry}
          material={materials["Material.026"]}
          skeleton={nodes.NurbsPath011.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Vert001.geometry}
          material={materials.Skin}
          skeleton={nodes.Vert001.skeleton}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={20.86}
        position={[-5.09, 4.08, 6.58]}
        rotation={[-0.16, -0.48, -0.08]}
      />
      <pointLight
        intensity={5}
        decay={2}
        position={[2.41, 1.86, -2.68]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={5}
        decay={2}
        position={[2.43, 0.74, -2.68]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={5}
        decay={2}
        position={[-1.65, 0.74, -3.09]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[0.27, 1.5, -3.09]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={5}
        decay={2}
        position={[-1.66, 1.7, -3.09]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials["Material.005"]}
        position={[-0.05, 1.33, -0.89]}
        rotation={[Math.PI, -1.57, Math.PI]}
        scale={[0.83, 0.17, 0.83]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069_1.geometry}
          material={materials["Material.005"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.002"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.015"]}
        position={[0.01, 2.37, -2.82]}
        scale={[0.93, 0.92, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.015"]}
        position={[-1.74, 1.39, -2.82]}
        scale={[0.92, 0.92, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.015"]}
        position={[-1.74, 1.4, -2.82]}
        scale={[0.91, 0.91, 0.99]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.015"]}
        position={[-1.74, 0.27, -2.82]}
        scale={[0.91, 0.91, 0.99]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.004"]}
        position={[0.67, 2.49, -2.34]}
        rotation={[0, -0.02, 0]}
        scale={[-0.08, -0.06, -0.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Material.026"]}
        position={[-0.25, 2.47, -2.39]}
        rotation={[-3.04, 0, Math.PI]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.005"]}
        position={[-0.25, 2.45, -2.42]}
        scale={[0.57, 0.92, 0.23]}
      />
      <group
        position={[-1.02, 3.21, -3.12]}
        rotation={[0, -1.23, 0]}
        scale={[1.24, 1.18, 1.24]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials["Material.001"]}
          position={[-0.07, -0.57, -0.01]}
          scale={[0.69, 0.72, 0.69]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.005"]}
        position={[-1, 3.7, -3.08]}
        rotation={[Math.PI / 2, 0, -0.34]}
        scale={0.36}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["Material.010"]}
          position={[5.29, 0, 0.43]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.010"]}
          position={[0, 0, 2.88]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials["Material.014"]}
          position={[-2.32, 0.01, 0.09]}
          scale={0.12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials["Material.010"]}
          position={[0, 0, 0.43]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials["Material.010"]}
          position={[0, 0, 0.44]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials["Material.011"]}
          position={[-0.25, 0, 1.4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials["Material.001"]}
          position={[0.02, 0.02, 0.94]}
          scale={0.34}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials["Material.032"]}
          position={[0.02, 0.02, 0.7]}
          scale={0.34}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials["Material.005"]}
          position={[0, 0, 2.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials.Material}
          position={[0, 0, 0.17]}
        />
      </mesh>
      <group
        position={[1.68, 2.45, -2.43]}
        rotation={[2.39, 1.16, -0.89]}
        scale={[-0.02, -0.19, -0.02]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro_1.geometry}
          material={materials.metalizado}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro_2.geometry}
          material={materials["goma.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro_3.geometry}
          material={materials.cromado}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro_4.geometry}
          material={materials["punta boli"]}
        />
      </group>
      <group
        position={[-2.05, 2.44, -2.49]}
        rotation={[1.18, -0.82, -0.52]}
        scale={[0.01, 0.18, 0.01]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro001.geometry}
          material={materials["madera azul"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro001_1.geometry}
          material={materials.aluminio}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro001_2.geometry}
          material={materials.madera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro001_3.geometry}
          material={materials.goma}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro001_4.geometry}
          material={materials.mina}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cilindro001_5.geometry}
          material={materials.blanco}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.enganche_boli.geometry}
        material={materials.metalizado}
        position={[1.7, 2.46, -2.36]}
        rotation={[-0.75, -1.16, -0.68]}
        scale={[0.04, 0.04, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GOMA.geometry}
        material={materials.CAJA2}
        position={[-2.3, 2.49, -2.39]}
        rotation={[0, -0.79, 0]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["inner mouth"]}
        position={[1.86, 2.44, -2.45]}
        rotation={[0, -0.01, 0]}
        scale={0.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.017"]}
        position={[-0.74, 0.66, 0.47]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["FlowerStalk.001"]}
        position={[-0.74, 0.66, -0.5]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.032"]}
        position={[-0.74, 0.66, -1.43]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.017"]}
        position={[-0.74, -0.04, -1.04]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.019"]}
        position={[-0.74, -0.04, -0.06]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials["Material.007"]}
        position={[-0.78, 0.5, 0.47]}
        rotation={[0, 0, -1.66]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials["Material.017"]}
        position={[-0.78, 0.5, -1.43]}
        rotation={[0, 0, -1.66]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials["Material.019"]}
        position={[-0.78, 0.5, -0.5]}
        rotation={[0, 0, -1.66]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials["Material.032"]}
        position={[-0.78, -0.2, -0.05]}
        rotation={[0, 0, -1.66]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials["Material.023"]}
        position={[-0.78, -0.2, -1.05]}
        rotation={[0, 0, -1.66]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[0.01, 5.6, -4.22]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.025"]}
        position={[0.01, 5.59, -4.15]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.025"]}
        position={[0.01, 5.59, -4.15]}
        rotation={[Math.PI / 2, 0.41, Math.PI / 2]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-0.01, 7.57, 9.76]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.Skin}
        position={[-0.01, 3.69, -1.15]}
        rotation={[3.12, 0, -3.14]}
        scale={[0.36, 0.36, 0.33]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials.Skin}
          position={[0, -0.27, 0.83]}
          scale={[0.11, 0.11, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ears.geometry}
          material={materials.Skin}
          position={[0.71, -0.03, -0.06]}
          rotation={[1.44, -0.19, -1.11]}
          scale={[3.84, 4.42, 5.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath006.geometry}
          material={materials["inner mouth"]}
          position={[0.01, -0.51, 0.82]}
          scale={[0.1, 0.15, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath010.geometry}
          material={materials["Skin.001"]}
          position={[-0.29, 0.06, 0.81]}
          scale={[0.08, 0.1, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["eyes.001"]}
          position={[-0.28, -0.06, 0.81]}
          scale={[4.82, 5.25, 4.14]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials["Material.006"]}
        position={[-0.01, 1.67, -1.01]}
        rotation={[-3.1, 0, Math.PI]}
        scale={[0.47, 0.42, 0.42]}
      />
      <group
        position={[1.15, 3.21, -3.13]}
        rotation={[Math.PI, -1.29, Math.PI]}
        scale={[1.24, 1.18, 1.24]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["Material.015"]}
          position={[-0.07, -0.57, -0.01]}
          scale={[0.69, 0.72, 0.69]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials["Material.021"]}
          position={[0.02, 0.28, 0.63]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials["Material.022"]}
          position={[0.02, 0.13, 0.63]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials["Material.032"]}
          position={[0.03, -0.31, 0.58]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.03, 0.03, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials["Material.001"]}
          position={[0.02, 0.31, -0.01]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.25, 0.02, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials["Material.001"]}
          position={[0.02, 0.23, -0.01]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.25, 0.02, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={materials["Material.021"]}
          position={[0.02, -0.31, -0.01]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.25, 0.02, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023.geometry}
          material={materials.Material}
          position={[0.03, -0.28, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.8, 0.8, 0.85]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Skin.001"]}
        position={[-0.01, 3.69, -1.15]}
        rotation={[3.12, 0, -3.14]}
        scale={[0.36, 0.36, 0.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={materials["Skin.001"]}
        position={[0, 3.94, -1.43]}
        rotation={[0.18, 0, 0]}
        scale={[0.16, 0.85, 0.77]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath002.geometry}
        material={materials["Skin.001"]}
        position={[0, 4.01, -1.29]}
        rotation={[0.63, 0, 0]}
        scale={[0.16, 0.85, 0.77]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        position={[0, -0.07, 0.91]}
        scale={5.29}
      />
    </group>
  );
}

useGLTF.preload("/hero.glb");

