/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function MeetingModel(props) {
  const { nodes, materials } = useGLTF("/meeting.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.98, -0.74, 1.28]}
        rotation={[-1.57, -1.51, -1.57]}
        scale={1.67}
      >
        <primitive object={nodes.spine} />
        <primitive object={nodes.neutral_bone} />
        <primitive object={nodes.neutral_bone_1} />
        <primitive object={nodes.neutral_bone_2} />
        <primitive object={nodes.neutral_bone_3} />
        <primitive object={nodes.neutral_bone_4} />
        <skinnedMesh
          geometry={nodes.Cube034.geometry}
          material={materials["Material.007"]}
          skeleton={nodes.Cube034.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube035.geometry}
          material={materials["Skin.004"]}
          skeleton={nodes.Cube035.skeleton}
        />
        <skinnedMesh
          geometry={nodes.M_Hips.geometry}
          material={materials["Skin.003"]}
          skeleton={nodes.M_Hips.skeleton}
        />
        <skinnedMesh
          geometry={nodes.NurbsPath011.geometry}
          material={materials["Material.007"]}
          skeleton={nodes.NurbsPath011.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Vert001.geometry}
          material={materials["Skin.003"]}
          skeleton={nodes.Vert001.skeleton}
        />
      </group>
      <group
        position={[-2.07, -0.74, -2.94]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.68}
      >
        <primitive object={nodes.spine_1} />
        <primitive object={nodes.neutral_bone_5} />
        <primitive object={nodes.neutral_bone_6} />
        <primitive object={nodes.neutral_bone_7} />
        <primitive object={nodes.neutral_bone_8} />
        <primitive object={nodes.neutral_bone_9} />
        <skinnedMesh
          geometry={nodes.Cube033.geometry}
          material={materials["Rubber.002"]}
          skeleton={nodes.Cube033.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube043.geometry}
          material={materials["PANTS.002"]}
          skeleton={nodes.Cube043.skeleton}
        />
        <skinnedMesh
          geometry={nodes.M_Hips001.geometry}
          material={materials["Skin.006"]}
          skeleton={nodes.M_Hips001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.NurbsPath005.geometry}
          material={materials["Lace.001"]}
          skeleton={nodes.NurbsPath005.skeleton}
        />
        <skinnedMesh
          geometry={nodes.NurbsPath005_1.geometry}
          material={materials["Rubber.002"]}
          skeleton={nodes.NurbsPath005_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Vert002.geometry}
          material={materials["Skin.006"]}
          skeleton={nodes.Vert002.skeleton}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.9}
        position={[11.78, 5.27, -13.76]}
        rotation={[-2.9, 0.72, 2.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["material.002"]}
        position={[-0.41, 1.57, 0]}
        scale={[1.37, 0.93, 1.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-0.35, -0.12, 0.06]}
        scale={[2.18, 3.96, 5.09]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.012"]}
        position={[-6.87, 3.8, -0.4]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Material.012"]}
        position={[-6.87, 3.8, 3.22]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials["Material.011"]}
        position={[0.13, 1.63, -1]}
        rotation={[3.14, -1.39, -0.01]}
        scale={[0.31, 0.48, 0.21]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen003.geometry}
          material={materials["Material.003"]}
          position={[0, -0.01, 0]}
          scale={0.93}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body001.geometry}
        material={materials["Material.011"]}
        position={[0.39, 1.63, -3.12]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.32, 0.21, 0.21]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Keyboard001.geometry}
          material={materials["Material.011"]}
          position={[0.72, 0.04, 0.13]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.04, 0.03, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen001.geometry}
          material={materials["Material.011"]}
          position={[0, 0.08, -0.94]}
          rotation={[-1.77, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hinge001.geometry}
            material={materials["Material.011"]}
            position={[0, 0.04, -0.02]}
            rotation={[1.57, 0, 0]}
            scale={[0.99, 1, 1]}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body002.geometry}
        material={materials["Material.011"]}
        position={[0.22, 1.63, 1.23]}
        rotation={[-Math.PI, 1.5, -Math.PI]}
        scale={[0.32, 0.21, 0.21]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Keyboard002.geometry}
          material={materials["Material.011"]}
          position={[0.72, 0.04, 0.13]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.04, 0.03, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen002.geometry}
          material={materials["Material.011"]}
          position={[0, 0.08, -0.94]}
          rotation={[-1.77, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hinge002.geometry}
            material={materials["Material.011"]}
            position={[0, 0.04, -0.02]}
            rotation={[1.57, 0, 0]}
            scale={[0.99, 1, 1]}
          />
        </mesh>
      </mesh>
      <group
        position={[-6.27, 0.65, 1.45]}
        rotation={[1.57, -1.55, 1.57]}
        scale={0.4}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["material.002"]}
        />
      </group>
      <group
        position={[-6.27, 0.65, -1.12]}
        rotation={[1.57, -1.55, 1.57]}
        scale={0.4}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials["material.002"]}
        position={[-6.46, 1.43, 3.24]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["material.002"]}
        position={[-6.46, 1.43, 1.67]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["material.002"]}
        position={[-6.46, 0.29, -0.12]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["material.002"]}
        position={[-6.46, 0.29, -2.23]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15051.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, -2.3]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11051.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15052.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -2.22]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11052.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15053.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, -2.13]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11053.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15054.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -2.45]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11054.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15055.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, -2.38]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11055.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15056.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, -2.69]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11056.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15057.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -2.61]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11057.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15058.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, -2.53]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11058.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15059.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -2.85]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11059.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15060.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, -2.77]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11060.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15061.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, -1.51]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11061.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15062.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -1.43]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11062.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15063.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, -1.35]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11063.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15064.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -1.67]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11064.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15065.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, -1.59]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11065.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15066.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, -1.91]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11066.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15067.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -1.83]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11067.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15068.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, -1.75]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11068.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15069.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -2.07]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11069.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15070.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, -1.99]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11070.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15071.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, 0.28]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11071.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15072.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 0.36]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11072.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15073.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 0.44]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11073.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15074.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 0.12]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11074.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15075.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, 0.2]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11075.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15076.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, -0.12]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11076.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15077.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -0.04]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11077.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15078.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 0.04]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11078.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15079.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, -0.33]}
        rotation={[-2.98, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11079.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15080.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, -0.2]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11080.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15081.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, 1.3]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11081.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15082.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 1.38]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11082.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15083.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 1.47]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11083.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15084.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 1.15]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11084.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15085.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, 1.22]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11085.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15086.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, 0.91]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11086.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15087.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 0.99]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11087.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15088.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 1.07]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11088.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15089.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 0.75]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11089.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15090.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, 0.83]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11090.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15094.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 1.93]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11094.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15096.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, 1.69]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11096.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15097.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 1.77]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11097.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15098.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 1.85]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11098.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15099.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 1.53]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11099.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15100.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, 1.61]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11100.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15101.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 2.91, 3.88]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11101.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15102.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 3.96]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11102.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15103.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 4.04]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11103.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15104.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 2.91, 3.72]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11104.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15105.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 2.91, 3.8]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11105.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15108.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 2.91, 3.64]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11108.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15091.geometry}
        material={materials["Material.023"]}
        position={[-5.93, 2.91, 2.11]}
        rotation={[2.87, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11091.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <group
        position={[-6.27, 0.65, 3.25]}
        rotation={[1.57, -1.55, 1.57]}
        scale={0.4}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15092.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.75, -2.88]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11092.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15093.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 1.75, -2.8]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11093.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15095.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.75, -2.34]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11095.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15106.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 1.75, -2.58]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11106.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15107.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.75, -2.5]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11107.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15109.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 1.75, -2.42]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11109.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15110.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.75, -2.73]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11110.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15111.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 1.75, -2.66]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11111.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15112.geometry}
        material={materials["material.001"]}
        position={[-5.93, 1.75, -2.16]}
        rotation={[2.87, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11112.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.006"]}
        position={[1.49, -0.14, -0.65]}
        scale={8.65}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15009.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 1.74, 0.28]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11009.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15010.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.74, 0.36]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11010.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15011.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 1.74, 0.44]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11011.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15012.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.74, 0.12]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11012.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15013.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 1.74, 0.2]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11013.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15014.geometry}
        material={materials["Material.023"]}
        position={[-5.94, 1.74, -0.12]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11014.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15015.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.74, -0.04]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11015.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15016.geometry}
        material={materials["Material.020"]}
        position={[-5.93, 1.74, 0.04]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11016.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15017.geometry}
        material={materials["Material.019"]}
        position={[-5.94, 1.74, -0.33]}
        rotation={[-2.98, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11017.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15018.geometry}
        material={materials["Material.020"]}
        position={[-5.94, 1.74, -0.2]}
        rotation={[-3.14, -0.03, -0.26]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11018.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials["Material.017"]}
        position={[1.21, 0.8, -3.06]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair001.geometry}
        material={materials["Material.017"]}
        position={[1.21, 0.8, -0.88]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair002.geometry}
        material={materials["Material.017"]}
        position={[1.21, 0.8, 1.27]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair003.geometry}
        material={materials["Material.017"]}
        position={[1.21, 0.8, 3.35]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair004.geometry}
        material={materials["Material.017"]}
        position={[-2.03, 0.8, 3.33]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair005.geometry}
        material={materials["Material.017"]}
        position={[-2.03, 0.8, 1.16]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair006.geometry}
        material={materials["Material.017"]}
        position={[-2.03, 0.8, -0.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair007.geometry}
        material={materials["Material.017"]}
        position={[-2.03, 0.8, -3.07]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.59, 0.12, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials["Material.017"]}
          position={[0.21, 6.03, 0]}
          scale={[0.12, 3.72, 0.71]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016.geometry}
          material={materials["Steel Black Polished"]}
          position={[-0.27, -2.65, 0]}
          scale={[0.17, 0.51, 0.17]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={nodes.Cube038.material}
        position={[9.65, 5.96, -12.77]}
        rotation={[0, -1.32, 0]}
        scale={0.18}
      />
      <group
        position={[-0.44, 5.22, 7.81]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.11}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials["material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials["Material.017"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen004.geometry}
        material={materials["Material.011"]}
        position={[-1.24, 1.63, 1.15]}
        rotation={[3.14, -1.39, -0.01]}
        scale={[0.31, 0.48, 0.21]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen005.geometry}
          material={materials["Material.003"]}
          position={[0, -0.01, 0]}
          scale={0.93}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen006.geometry}
        material={materials["Material.011"]}
        position={[-1.24, 1.63, -3.1]}
        rotation={[3.14, -1.39, -0.01]}
        scale={[0.31, 0.48, 0.21]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen007.geometry}
          material={materials["Material.003"]}
          position={[0, -0.01, 0]}
          scale={0.93}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body003.geometry}
        material={materials["Material.011"]}
        position={[0.15, 1.63, 3.31]}
        rotation={[-Math.PI, 1.5, -Math.PI]}
        scale={[0.32, 0.21, 0.21]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Keyboard003.geometry}
          material={materials["Material.011"]}
          position={[0.72, 0.04, 0.13]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.04, 0.03, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen008.geometry}
          material={materials["Material.011"]}
          position={[0, 0.08, -0.94]}
          rotation={[-1.77, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath002.geometry}
        material={materials["Skin.004"]}
        position={[0.92, 2.71, 1.29]}
        rotation={[1.94, 0.89, -2.04]}
        scale={[0.11, 0.6, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={materials["Skin.004"]}
        position={[0.83, 2.66, 1.32]}
        rotation={[2.58, 1.23, -2.6]}
        scale={[0.11, 0.6, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials["Material.013"]}
        position={[1.13, 1.05, 1.29]}
        rotation={[-1.57, -1.53, -1.57]}
        scale={[0.34, 0.3, 0.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials["Skin.003"]}
        position={[1.02, 2.49, 1.26]}
        rotation={[0.06, -1.29, 0.06]}
        scale={[0.25, 0.25, 0.24]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={materials["Skin.003"]}
          position={[0, -0.27, 0.83]}
          scale={[0.11, 0.11, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ears.geometry}
          material={materials["Skin.003"]}
          position={[0.71, -0.03, -0.06]}
          rotation={[1.44, -0.19, -1.11]}
          scale={[3.84, 4.42, 5.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath006_1.geometry}
          material={materials["inner mouth.002"]}
          position={[0.01, -0.51, 0.82]}
          scale={[0.1, 0.15, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath010.geometry}
          material={materials["Skin.004"]}
          position={[-0.29, 0.06, 0.81]}
          scale={[0.08, 0.1, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["eyes.003"]}
          position={[-0.28, -0.06, 0.81]}
          scale={[4.82, 5.25, 4.14]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        position={[5.5, 5.23, 1.29]}
        rotation={[0, -1.57, 0]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials["Skin.004"]}
        position={[1.02, 2.49, 1.26]}
        rotation={[0.06, -1.29, 0.06]}
        scale={[0.25, 0.25, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials["Skin.006"]}
        position={[-1.89, 2.51, -2.95]}
        rotation={[Math.PI / 2, 1.41, -Math.PI / 2]}
        scale={[0.26, 0.26, 0.24]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={materials["HAIR.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046.geometry}
          material={materials["Skin.006"]}
          position={[0, -0.27, 0.83]}
          scale={[0.11, 0.11, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ears001.geometry}
          material={materials["Skin.006"]}
          position={[0.71, -0.03, -0.06]}
          rotation={[1.44, -0.19, -1.11]}
          scale={[3.84, 4.42, 5.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath003_1.geometry}
          material={materials["HAIR.002"]}
          position={[-0.29, 0.06, 0.81]}
          scale={[0.08, 0.1, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath004.geometry}
          material={materials["inner mouth.004"]}
          position={[0.01, -0.51, 0.82]}
          scale={[0.09, 0.14, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001.geometry}
          material={materials["eyes.004"]}
          position={[-0.28, -0.06, 0.81]}
          scale={[4.82, 5.25, 4.14]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={nodes.Cube047.material}
        position={[-1.77, 4.89, -2.95]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.15}
      />
    </group>
  );
}

useGLTF.preload("/meeting.glb");
