/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function TubeModel(props) {
  const { nodes, materials } = useGLTF("/tube.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[12.2, 3.01, 19.38]}
        rotation={[Math.PI, -0.67, Math.PI]}
        scale={5.52}
      >
        <primitive object={nodes.spine} />
        <primitive object={nodes.neutral_bone} />
        <primitive object={nodes.neutral_bone_1} />
        <primitive object={nodes.neutral_bone_2} />
        <primitive object={nodes.neutral_bone_3} />
        <primitive object={nodes.neutral_bone_4} />
        <skinnedMesh
          geometry={nodes.Cube.geometry}
          material={materials.botol}
          skeleton={nodes.Cube.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube023.geometry}
          material={materials.botol}
          skeleton={nodes.Cube023.skeleton}
        />
        <skinnedMesh
          geometry={nodes.M_Hips.geometry}
          material={materials.botol}
          skeleton={nodes.M_Hips.skeleton}
        />
        <skinnedMesh
          geometry={nodes.NurbsPath011.geometry}
          material={materials.botol}
          skeleton={nodes.NurbsPath011.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Vert001.geometry}
          material={materials.botol}
          skeleton={nodes.Vert001.skeleton}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={22.9}
        position={[-28.05, 12.47, -11.18]}
        rotation={[-3, -1.07, -3.02]}
      />
      <group
        position={[13.4, 1.35, 20.05]}
        rotation={[Math.PI, -0.04, Math.PI]}
        scale={4.39}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0.77, 32.74, 3.94]}
        rotation={[0, -1.55, 0]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["material.001"]}
        position={[30.49, 3.57, 12.12]}
        rotation={[0, -1.57, 0]}
        scale={[0.98, 0.98, 4.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.PANTS}
        position={[27.87, 3.51, 5.73]}
        rotation={[0, -1.57, 0]}
        scale={[0.22, 0.22, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["material.001"]}
        position={[32.33, 7.84, 12.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 0.98, 4.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["16808_Microscope_v1"].geometry}
        material={materials["Material.016"]}
        position={[32.74, 9.97, 14]}
        rotation={[0, -0.96, 0]}
        scale={0.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["botol.004"]}
        position={[32.36, 10.26, 6.97]}
        rotation={[0, -1.57, 0]}
        scale={[0.22, 1.28, 0.23]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["Material.021"]}
          position={[0, 0.03, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.kayu}
        position={[32.15, 8.67, 3.39]}
        rotation={[0, -1.57, 0]}
        scale={[0.74, 0.98, 0.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["botol.001"]}
        position={[32.15, 9.12, 3.39]}
        rotation={[0, -1.57, 0]}
        scale={[0.74, 0.98, 0.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["botol.003"]}
        position={[32.37, 10.26, 7.7]}
        rotation={[0, -1.57, 0]}
        scale={[0.22, 1.28, 0.23]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["Material.018"]}
          position={[0, 0.03, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["botol.002"]}
        position={[32.37, 10.26, 8.43]}
        rotation={[0, -1.57, 0]}
        scale={[0.22, 1.28, 0.23]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials.Material}
          position={[0, 0.03, 0]}
        />
      </mesh>
      <group
        position={[32.35, 10.57, 8.07]}
        rotation={[0, -1.57, 0]}
        scale={[1.95, 0.1, 0.91]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials.botol}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["Material.006"]}
        position={[33, 8.14, 6.34]}
        rotation={[0, -1.57, 0]}
        scale={[0.12, 0.13, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["Material.006"]}
        position={[32.35, 8.8, 8.07]}
        rotation={[0, -1.57, 0]}
        scale={[1.95, 0.11, 0.91]}
      />
      <group
        position={[32.23, 10.06, 19.11]}
        rotation={[1.37, -1.55, 1.37]}
        scale={[1.55, 1.83, 1.83]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["material.002"]}
        position={[30.48, -0.09, 11.49]}
        rotation={[0, -1.57, 0]}
        scale={1.25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15075.geometry}
        material={materials["Material.020"]}
        position={[29.14, 1.84, 11.62]}
        rotation={[1.57, -0.03, -0.25]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11075.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15073.geometry}
        material={materials["Material.020"]}
        position={[29.15, 2.28, 11.62]}
        rotation={[1.57, -0.03, -0.25]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11073.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15072.geometry}
        material={materials["Material.019"]}
        position={[29.15, 2.13, 11.62]}
        rotation={[1.57, -0.03, -0.25]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11072.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15071.geometry}
        material={materials["Material.023"]}
        position={[29.14, 1.99, 11.62]}
        rotation={[1.57, -0.03, -0.25]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11071.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15001.geometry}
        material={materials["Material.020"]}
        position={[28.68, 4.37, 14.84]}
        rotation={[3.14, 0.03, 2.9]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11001.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15002.geometry}
        material={materials["Material.020"]}
        position={[28.67, 4.37, 15.28]}
        rotation={[3.14, 0.03, 2.9]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11002.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15003.geometry}
        material={materials["Material.019"]}
        position={[28.68, 4.37, 15.13]}
        rotation={[3.14, 0.03, 2.9]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11003.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polymsh15004.geometry}
        material={materials["Material.023"]}
        position={[28.68, 4.37, 14.99]}
        rotation={[3.14, 0.03, 2.9]}
        scale={[0.08, 0.07, 0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube11004.geometry}
          material={materials.material}
          position={[-4.63, -1.13, -0.02]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials["material.002"]}
        position={[30.48, 3.83, 11.49]}
        rotation={[0, -1.57, 0]}
        scale={1.25}
      />
      <group
        position={[13.4, 18.72, 20.05]}
        rotation={[Math.PI, -0.04, Math.PI]}
        scale={5.19}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={materials["Material.003"]}
        position={[10.87, 0, 26.4]}
        rotation={[-3.01, -0.04, 3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001.geometry}
        material={materials["Material.005"]}
        position={[10.87, 0.72, 26.4]}
        rotation={[-3.01, -0.04, 3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[12.64, -0.64, 2.88]}
        rotation={[0, -0.03, 0]}
        scale={26.33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[13.03, 26.55, 19.81]}
        rotation={[Math.PI, -0.81, Math.PI]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ears.geometry}
        material={materials.botol}
        position={[11.48, 13.7, 19.46]}
        rotation={[1.82, 0.06, 1.36]}
        scale={[3.05, 3.67, 4.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[12.05, 26.81, 19.23]}
        rotation={[Math.PI, -0.67, Math.PI]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.botol}
        position={[11.52, 13.5, 18.53]}
        rotation={[Math.PI, -0.67, Math.PI]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.botol}
        position={[11.92, 13.73, 19.05]}
        rotation={[Math.PI, -0.67, Math.PI]}
        scale={[0.84, 0.84, 0.78]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials["Material.002"]}
        position={[12.24, 9.03, 19.47]}
        rotation={[Math.PI, -0.67, Math.PI]}
        scale={[1.11, 0.99, 0.99]}
      />
    </group>
  );
}

useGLTF.preload("/tube.glb");